
import { EventData, PackingList, IngredientType } from '../types';

export const generateEventBriefText = (event: EventData, list: PackingList | null): string => {
    let body = `EVENT BRIEF & PACKING LIST\n`;
    body += `==================================================\n\n`;
    
    body += `[ EVENT DASHBOARD ]\n`;
    body += `--------------------------------------------------\n`;
    body += `CLIENT:     ${event.clientName}\n`;
    body += `PHONE:      ${event.clientPhone || 'N/A'}\n`;
    body += `PAYMENT:    ${event.isPaid ? 'PAID' : 'UNPAID'}\n`;
    body += `DATE:       ${new Date(event.eventDate).toLocaleDateString()}\n`;
    body += `TIME:       ${new Date(event.eventDate).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})} - ${new Date(event.endTime).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}\n`;
    body += `LOCATION:   ${event.location}\n`;
    body += `HEADCOUNT:  ${event.headcount} Guests\n`;
    body += `TYPE:       ${event.eventType}\n`;
    body += `BARTENDER:  ${event.bartender.name} (${event.bartender.email})\n\n`;
    
    body += `[ LOGISTICS ]\n`;
    body += `--------------------------------------------------\n`;
    body += `MOBILE BAR: ${event.barRental.required ? `YES (${event.barRental.size}, ${event.barRental.color})` : 'NO - Not Required'}\n`;
    body += `GLASSWARE:  ${event.glassRental.required ? `YES (Rental)` : 'NO (Plastic Cups)'}\n`;
    body += `ALCOHOL:    ${event.clientSuppliesAlcohol ? 'CLIENT SUPPLIED' : 'MTL CRAFT SUPPLIED'}\n\n`;
    
    body += `[ SELECTED COCKTAILS ]\n`;
    body += `--------------------------------------------------\n`;
    event.cocktailSelections.forEach(c => body += `• ${c}\n`);
    body += `\n`;
    
    if (list) {
        body += `[ MASTER PACKING LIST ]\n`;
        body += `==================================================\n`;
        body += `TOTAL DRINKS: ${list.summary.totalDrinks}\n\n`;

        Object.keys(list.categories).forEach(key => {
            const type = key as IngredientType;
            const items = list.categories[type];
            if (items && items.length > 0) {
                body += `[ ${type.toUpperCase()} ]\n`;
                body += `------------------------\n`;
                items.forEach(item => {
                    let line = `- ${item.name}: ${item.containersNeeded} ${item.containersNeeded > 1 ? 'units' : 'unit'}`;
                    // Only show volume detail if > 0 (avoids "0 cans")
                    if (item.quantityNeededOz > 0) {
                        line += ` (${Math.round(item.quantityNeededOz * 10) / 10} ${item.unit})`;
                    }
                    body += `${line}\n`;
                });
                body += `\n`;
            }
        });
    } else {
        body += `[ PACKING LIST NOT GENERATED ]\n`;
        body += `Please generate the packing list in the app first.\n`;
    }
    
    body += `==================================================\n`;
    body += `Auto-generated by MTL Craft Cocktails AI.`;

    return body;
};
